@startuml

title __CONNECTION's Class Diagram__\n

  namespace com.blackhearth.securevoipclient {
    namespace client {
      namespace connection {
        class com.blackhearth.securevoipclient.client.connection.BasicClientConnector {
            - restTemplate : RestTemplate
            + BasicClientConnector()
            + acceptConnection()
            + disconnect()
            + refuseConnection()
            + tryConnectWith()
        }
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace client {
      namespace connection {
        class com.blackhearth.securevoipclient.client.connection.ConnectionConstants {
            {static} ~ ACCEPT_CONNECTION_ENDPOINT : String
            {static} ~ DISCONNECT_ENDPOINT : String
            {static} ~ REFUSE_CONNECTION_ENDPOINT : String
            {static} ~ TRY_CONNECTION_ENDPOINT : String
            - ConnectionConstants()
        }
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace client {
      namespace connection {
        interface com.blackhearth.securevoipclient.client.connection.ConnectionService {
            {abstract} + acceptConnection()
            {abstract} + disconnect()
            {abstract} + refuseConnection()
            {abstract} + tryConnectWith()
        }
      }
    }
  }
  

  com.blackhearth.securevoipclient.client.connection.BasicClientConnector .up.|> com.blackhearth.securevoipclient.client.connection.ConnectionService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
