@startuml

title __COMMUNICATION's Class Diagram__\n

  namespace  {
    namespace om.bluevortexflare.securevoip {
      namespace communication {
        class com.bluevortexflare.securevoip.communication.BasicCommunicationForwarderService {
            - PORT : int
            {static} - log : Logger
            - message : byte[]
            - socket : DatagramSocket
            - users : List<VoIPUser>
            + BasicCommunicationForwarderService()
            + makeCall()
            + run()
            + sendRefuseMessage()
            - forwardDatagram()
            - getInitiatorNickFromToken()
            - receiveDatagram()
            - sendMessageToAllUsers()
            - sendMessageToUser()
            - setUserInetAddressIfTokenReceived()
        }
      }
    }
  }
  

  namespace  {
    namespace om.bluevortexflare.securevoip {
      namespace communication {
        interface com.bluevortexflare.securevoip.communication.CommunicationForwarderService {
            {abstract} + makeCall()
            {abstract} + run()
            {abstract} + sendRefuseMessage()
        }
      }
    }
  }
  

  com.bluevortexflare.securevoip.communication.BasicCommunicationForwarderService .up.|> com.bluevortexflare.securevoip.communication.CommunicationForwarderService
  com.bluevortexflare.securevoip.communication.BasicCommunicationForwarderService o-- com.bluevortexflare.securevoip.session.UserSessionService : sessionService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
