@startuml

title __REGISTER's Class Diagram__\n

  namespace com.blackhearth.securevoipclient {
    namespace client {
      namespace register {
        class com.blackhearth.securevoipclient.client.register.BasicClientRegister {
            - restTemplate : RestTemplate
            + BasicClientRegister()
            + getData()
            + getRestTemplate()
            + registerUser()
        }
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace client {
      namespace register {
        class com.blackhearth.securevoipclient.client.register.RegisterConstants {
            {static} ~ FILE_NAME : String
            {static} ~ ONE : int
            {static} ~ REGISTER_ENDPOINT : String
            {static} ~ THREE : int
            {static} ~ TWO : int
            {static} ~ ZERO : int
        }
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace client {
      namespace register {
        class com.blackhearth.securevoipclient.client.register.RegisterException {
            + RegisterException()
        }
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace client {
      namespace register {
        interface com.blackhearth.securevoipclient.client.register.RegisterService {
            {abstract} + registerUser()
        }
      }
    }
  }
  

  com.blackhearth.securevoipclient.client.register.BasicClientRegister .up.|> com.blackhearth.securevoipclient.client.register.RegisterService
  com.blackhearth.securevoipclient.client.register.BasicClientRegister o-- com.blackhearth.securevoipclient.client.BasicClientData : data


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
