@startuml

title __REGISTER's Class Diagram__\n

    namespace com.bluevortexflare.securevoip {
      namespace users {
        namespace register {
          class com.bluevortexflare.securevoip.users.register.BasicUserRegisterService {
              - seqNumber : AtomicInteger
              - users : List<VoIPUser>
              + registerUser()
              - addToWaitingRoom()
              - generateNickFromRequest()
          }
        }
      }
    }


    namespace com.bluevortexflare.securevoip {
      namespace users {
        namespace register {
          interface com.bluevortexflare.securevoip.users.register.UserRegisterService {
              {abstract} + registerUser()
          }
        }
      }
    }

  

    namespace com.bluevortexflare.securevoip {
      namespace users {
        namespace register {
          class com.bluevortexflare.securevoip.users.register.VoIPUser {
              - addressIp : InetAddress
              - id : int
              - nick : String
              - publicKey : String
              - readyToTalk : boolean
              - userToken : String
              + getAddressIp()
              + getId()
              + getNick()
              + getPublicKey()
              + getUserToken()
              + isReadyToTalk()
              + setAddressIp()
              + setId()
              + setNick()
              + setPublicKey()
              + setReadyToTalk()
              + setUserToken()
          }
        }
      }
    }

  

    namespace com.bluevortexflare.securevoip {
      namespace users {
        namespace register {
          class com.bluevortexflare.securevoip.users.register.WaitingRoomConfig {
              + waitingRoom()
          }
        }
      }
    }
  
  

  com.bluevortexflare.securevoip.users.register.BasicUserRegisterService .up.|> com.bluevortexflare.securevoip.users.register.UserRegisterService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
