@startuml

title __RSA's Class Diagram__\n

  namespace com.blackhearth.securevoipclient {
    namespace rsa {
      class com.blackhearth.securevoipclient.rsa.BasicConverter {
          + privateKeyFromString()
          + publicKeyFromString()
          + stringFromPrivateKey()
          + stringFromPublicKey()
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace rsa {
      class com.blackhearth.securevoipclient.rsa.ConverterRuntimeException {
          + ConverterRuntimeException()
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace rsa {
      class com.blackhearth.securevoipclient.rsa.RSAGenerator {
          - privateKey : PrivateKey
          - publicKey : PublicKey
          + decrypt()
          + encrypt()
          + getPrivateKey()
          + getPublicKey()
          + init()
          + setPrivateKey()
          + setPublicKey()
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace rsa {
      class com.blackhearth.securevoipclient.rsa.Random128bit {
          - random : Random
          - result : String
          + Random128bit()
          + getRandom()
          + getResult()
      }
    }
  }
  

  namespace com.blackhearth.securevoipclient {
    namespace rsa {
      interface com.blackhearth.securevoipclient.rsa.RsaCoverter {
          {abstract} + privateKeyFromString()
          {abstract} + publicKeyFromString()
          {abstract} + stringFromPrivateKey()
          {abstract} + stringFromPublicKey()
      }
    }
  }
  

  com.blackhearth.securevoipclient.rsa.BasicConverter .up.|> com.blackhearth.securevoipclient.rsa.RsaCoverter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
